### ISSUE TITLE
exclude logging backend library from dependencies

### ISSUE THREAD

**Issue by genmeblog** [pink-gorilla/webly#24]
Since `webly` is a library used by other projects (eg. notespace) it shouldn't include any logging backend as a dependency. It should depend only on frontend, having backend configuration in local environment only.
In current setup `webly` overwrites local logging configuration and causes problems.

**Comment by awb99** [comment]
@genmeblog  You are right! I use timbre for both clojure and clojurescript logging. 
Webly now only provides timbre logging config for cljs.
